apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  labels:
    app: rabbitmq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
      - name: rabbitmq-consumer
        image: frank58246/rabbitmq-consumer:0626c
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: staging
        - name: UNIQUE_QUEUE
          value: "y"          
        - name: DELAY_SECOND
          value: "0"           
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-consumer-service
spec:
  type: NodePort 
  selector:
    app: rabbitmq-consumer
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30006
