version: '3.7'
services:
  elastic_search:
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
    restart: always
    environment: 
      - SA_PASSWORD=qazwsx123456!
      - ACCEPT_EULA=Y

