apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volv
          mountPath: /usr/share/nginx/html
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: local-path-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort 
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30005
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
