version: '2'

services:
  rabbit1:
    container_name: rabbit1
    image: rabbitmq:3.9.20-management
    hostname: rabbit1
    restart: always
    volumes: 
      - "./data:/var/lib/rabbitmq/mnesia/"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234qwer
  rabbit2:
    container_name: rabbit2
    restart: always
    image: rabbitmq:3.9.20-management
    hostname: rabbit2
    links:
      - rabbit1
    environment: 
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
      - RAM_NODE=true
    volumes: 
      - "./data:/var/lib/rabbitmq/mnesia/"
    ports:
      - "5673:5672"
      - "15673:15672"    
  rabbit3:
    container_name: rabbit3
    image: rabbitmq:3.9.20-management
    restart: always
    hostname: rabbit3
    links:
      - rabbit1
      - rabbit2
    environment: 
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit1
    ports:
      - "5674:5672"
      - "15674:15672"    
    volumes: 
      - "./data:/var/lib/rabbitmq/mnesia/"