version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: host.docker.internal
    #restart: always
    privileged: true
    environment:
      - GITLAB_ROOT_PASSWORD=!pa55word
    ports:
      - '8080:80'
      - '443:443'
      - '22:22'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '~/gitlab/config:/etc/gitlab'
      - '~/gitlab/logs:/var/log/gitlab'
      - '~/gitlab/data:/var/opt/gitlab'
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: "gitlab-runner"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner/config.toml:/etc/gitlab-runner/config.toml