apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-poc
  labels:
    app: rabbitmq-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-poc
  template:
    metadata:
      labels:
        app: rabbitmq-poc
    spec:
      containers:
      - name: rabbitmq-poc
        image: frank58246/log-test
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-poc-service
spec:
  type: NodePort 
  selector:
    app: rabbitmq-poc
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30001
