apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  # append additional plugin to list here
  enabled_plugins: |
    [ rabbitmq_management, rabbitmq_prometheus].
  rabbitmq.conf: |
    listeners.tcp.default = 5672