version: '3.7'
services:
  elasticsearch:
    container_name: ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
    volumes:
      - ./data/:/usr/share/elasticsearch/data
    restart: always
    environment: 
    - discovery.type=single-node

  logstash:
    container_name: Logstash
    image: logstash:7.17.5
    # volumes:
    #   - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    #   - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch    

