version: '3.7'
services:
  elastic_search:
    container_name: ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
    volumes:
      - ./data/:/usr/share/elasticsearch/data
    restart: always
    environment: 
    - discovery.type=single-node

