version: "3.9"
services:
 
  sqlserver:
    ports:
      - 3309:3306
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
#    networks:
#      - demo-network
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d

networks:
  demo-network:
    
volumes: 
  sqlVolumes: